version: "3"
services:
  mongodb:
    image: mongo:4.1
    ports:
      - 27017:27017
  redis:
    image: redis

  identity-server:
    build: .
    ports:
      - 3000:3000
    # command: ["node", "./src/server.js"]
    environment:
      MONGO_CONNECTION_STRING: "mongodb://mongodb:27017/intuitiv"
      PORT: 3000
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis
