version: "3"
services:
  # mongodb:
  #   image: mongo:4.1
  #   ports:
  #     - 27017:27017
  redis:
    image: redis:5.0.7-alpine

  middleware-api:
    build: .
    ports:
      - 3002:3002
    # command: ["node", "./src/server.js"]
    environment:
      PORT: 3002
      REDIS_SERVER: redis
    depends_on:
      # - mongodb
      - redis
    links:
      # - mongodb
      - redis
